### PR TITLE
Add option to show social networks in folderish templates

### LINKED ISSUE #174: Show viewlet in specific Folders templates
I want to show the social like viewlet in a folder, only if it has a specific template as its default view. Today, if I set the folder to show the viewlet, it is a showed for all folders, regardless of what view is set to it.

### PR DESCRIPTION
**Pull request by idgserpro**
Even if folderish type isn't checked to show social networks.

Closes #174

### CODE REVIEW

**Comment by idgserpro** [comment]
Can anyone take a look here?

@hvelarde @ericof @rodfersou

**Comment by idgserpro** [comment]
Can anyone merge and create a new release?

**Comment by idgserpro** [comment]
@hvelarde looks like the new cover version is broken:

https://travis-ci.org/collective/sc.social.like/jobs/630044869#L1650

**Comment by hvelarde** [comment]
fixed: https://pypi.org/project/collective.cover/2.2.2/

**Pull request merged**
