### PR TITLE
add note re: Plone 5.0 compatibility, add PyPi classifier for Plone 5.0

### PR DESCRIPTION
**Pull request by tkimnguyen**
as per https://github.com/collective/sc.social.like/issues/99#issuecomment-445496307

### CODE REVIEW

**Comment by tkimnguyen** [comment]
Can you point me to the things you think are not working with 5.0.x?

**Comment by hvelarde** [comment]
ok, I trust you.

**Comment by idgserpro** [comment]
@hvelarde @tkimnguyen strange to say that it is compatible with Plone 5.0 without running tests on Plone 5.0:

https://github.com/collective/sc.social.like/commit/708ac654785d272ac828b8bd973deeb7287dd490

**Comment by hvelarde** [comment]
indeed, AFAIR package is not compatible with Plone 5.

**Pull request merged**
