### PR TITLE
Add Facebook control panel setting for showing/hiding the number of likes

### PR DESCRIPTION
**Pull request by fredvd**
By default the Facebook plugin still shows the number of likes.
Updated translation files and translated Dutch.

### CODE REVIEW

**Comment by hvelarde** [comment]
@fredvd what script are you using to update the translation files? there are a lot of unneeded changes.

**Comment by fredvd** [comment]
Translations:

I used the rebuildPO.sh script in the locales directory of sc.social.like and a locally installed i18ndude which is 4.0.1. Hmm it's updating the 'relative path of the locations as well.  I now see there's also a rebuild_i18n.sh script in the main buildout directory.  If that's the preferred one to use, should we remove rebuildPO.sh to avoid confusion?

**Comment by fredvd** [comment]
@hvelarde reran translation updates with the buildout script, more tests added.

**Comment by hvelarde** [comment]
thanks! give me some time because I'm doing something right now.

**Comment by hvelarde** [comment]
@fredvd I made a new release https://pypi.python.org/pypi/sc.social.like/2.9

**Pull request merged**
