### PR TITLE
Facebook share button

### PR DESCRIPTION
**Pull request by keul**
Same issue from PR #15 (but I have no power on the affinitic fork to continue with it).
Providing the Facebook "Share" button is very easy with the new HTML 5 code but I added this disabled by default.

There's a couple of new translations message to be filled (italian already done)

### CODE REVIEW

**Comment by keul** [comment]
Configuration note: right now the "Like" button is always shown while the "share" ones can be enabled/disabled.

If preferred I cal also change the checkbox button in a selection triplet like "show like only", "show share only", "show both".

**Comment by hvelarde** [comment]
don't you think is a good idea to add some test on this new feature?

**Comment by keul** [comment]
Yeah, absolutely. Just give me some hint on direction to take for configuration

**Comment by hvelarde** [comment]
probably just activate the share button and see that it is present on a rendered page

**Comment by keul** [comment]
@hvelarde sorry I meant something different (see my comment above). What about the configuration I did?
Right now a simple checkbox is displayed. It's acceptable or a selection of which button to display is better?

After this I can write tests.

**Comment by hvelarde** [comment]
@agnogueira @ericof @cleberjsantos comments on this?

**Comment by keul** [comment]
At the end I changed to code with an explicit selection of Like or Share button (see new screenshots for a preview), plus I fixed some other minor issues with i18n.

All done!

**Pull request merged**
