### PR TITLE
Make package compatible with Plone 5

### LINKED ISSUE #1: use plone.app.registry
we need to update the code to use plone.app.registry for the control panel.

this will break compatibility with Plone 3.x, but that has to be done at some point.

we will need also an upgrade step.

### PR DESCRIPTION
**Pull request by hvelarde**
## TODO

* [ ] fix Flake8
* [x] fix control panel tests
* [ ] fix plugin tests
* [ ] add upgrade step to handle migration from `portal_properties` to `plone.app.registry`
* [ ] check implications of new social viewlet in Plone 5

closes #1

### CODE REVIEW

**Comment by hvelarde** [comment]
@agitator I worked a little bit on this but in my opinion is going to be way more complex than expected, as expected; without tests passing I'm -1 on merging this so I would prefer to split in various minor PR:

* Move package configuration to plone.app.registry providing an upgrade step
* Implement CI build for plone.app.contenttypes on Plone 4.3 and fix all API inconsistencies
* Implement compatibility with Plone 5 (mainly resource registry stuff)

@keul @rodfersou comments?

**Comment by agitator** [comment]
i see the only problem in more complex tests
rather have a conditional test setup for at and dx, than to maintain two packages

**Comment by hvelarde** [comment]
@agitator current tests need refactoring; I think we start with the control panel refactoring and migration to plone.app.registry; after merging that we will be one step closer.

**Comment by keul** [comment]
@hvelarde no suggestion on my side, I didn't used sc.social.like recently (and never on Plone 5). But a big :+1:  to the idea to fix API inconsistence directly on the p.a.contenttypes core.

**Comment by jensens** [comment]
@hvelarde plone.directives.form is superfluos (since a while), all the directives were merged into plone.autoform and plone.supermodel. This works also in Plone 4.3 latest. IIRC the directives are deprecated anyway and are BBB imported in plone.directives.form.

**Comment by hvelarde** [comment]
closing this without merging because is too ambitious and not viable.

**Pull request closed without merging**
